### PR TITLE
Fixed rendering issues

### LINKED ISSUE #22: [Bug] b/d/h/k/l have uneven heights

### PR DESCRIPTION
**Pull request by emmamarichal**
Hi @erikdkennedy,

I checked files and found a couple of outlines issues that caused some rendering bugs (a small dot on the top of E, P, R)
Here is before/after: 
Capture d’écran 2023-02-22 à 15 51 19
Capture d’écran 2023-02-22 à 15 50 50

I also adjusted some outlines like here (the G):
Capture d’écran 2023-02-22 à 14 59 04
Capture d’écran 2023-02-22 à 15 01 58

I also fixed the issue #22 (h height problem)

Cheers! :)

fixes #22 #23

### CODE REVIEW

**Comment by tillsanders** [comment]
I'm not sure this is the same issue, but I noticed something similar with F, D, L and B. 

F

F

D

D

L

L

B

B

**Comment by tillsanders** [comment]
Sorry, forgot to mention – I was using the old version.

> Yes indeed, I took the opportunity to merge the outlines of complex letters, to avoid these problems. The rendering is much better

Looks very good indeed 👍

**Comment by emmamarichal** [comment]
@erikdkennedy Hi Erik! I think you can merge this so I can update the font :)

**Comment by erikdkennedy** [comment]
I've already made a few commits that I haven't pushed yet, including fixing the "h" height.

It'll take all my git skill to merge our changes 😛

Give me a bit here, but I'll get a new version pushed soon, and then submitted to GF soon after that 👍

**Comment by emmamarichal** [comment]
> I've already made a few commits that I haven't pushed yet, including fixing the "h" height.
Ah, I also updated this in my version :)

Ok no problem, tell me when it's ready! 👍

**Pull request merged**
